/**
 * Treatment Plan Service
 *
 * Generates AI-powered treatment plans with interventions, milestones, and outcomes.
 * PRD-9 compliant: Advisory only, no medical liability.
 *
 * Constraints:
 * - Claude API timeout: <30s
 * - Storage: clinical_status_json JSONB only
 * - NO PII in logs
 * - Disclaimers everywhere
 */

import Anthropic from "@anthropic-ai/sdk";
import type { IStorage } from "../storage";
import type {
  TreatmentPlan,
  TreatmentIntervention,
  TreatmentMilestone,
  CaseClinicalStatus,
  WorkerCase,
} from "@shared/schema";
import { fetchCaseContext } from "./smartSummary";
import { calculateRecoveryTimeline } from "./recoveryEstimator";
import { evaluateClinicalEvidence } from "./clinicalEvidence";
import { logAuditEvent } from "./auditLogger";
import { randomUUID } from "crypto";

const MODEL = "claude-sonnet-4-20250514";
const MAX_TOKENS = 3072;
const TIMEOUT_MS = 30000;

const DISCLAIMER_TEXT = `⚠️ ADVISORY ONLY

This treatment plan is generated by AI for care coordination purposes only. It does NOT constitute medical advice, diagnosis, or treatment recommendations.

All treatment decisions must be made by qualified healthcare professionals. This plan is intended to assist case managers in coordinating care and facilitating communication between stakeholders.

WorkSafe Victoria compliance: This is a coordination tool, not a medical directive.`;

/**
 * Sanitize user input to prevent prompt injection attacks
 * - Removes control characters that could break prompt structure
 * - Limits length (already enforced by Zod, but defensive)
 * - Escapes XML special characters for safe interpolation
 */
function sanitizeUserInput(input: string): string {
  return input
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "") // Remove control chars
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;")
    .substring(0, 5000); // Hard limit, even though Zod validates at 10000
}

export interface GenerateTreatmentPlanRequest {
  caseId: string;
  organizationId: string;
  additionalContext?: string;
}

export interface UpdateTreatmentPlanRequest {
  status?: "active" | "completed" | "archived";
  notes?: string;
}

interface AITreatmentPlanResponse {
  interventions: TreatmentIntervention[];
  milestones: TreatmentMilestone[];
  specialistReferrals?: string[];
  expectedDurationWeeks: number;
  expectedOutcomes: string[];
  successCriteria?: string[];
  factorsConsidered: string[];
}

/**
 * Build AI prompt for treatment plan generation
 */
function buildTreatmentPrompt(
  workerCase: WorkerCase,
  recoveryEstimate: any,
  clinicalFlags: string[],
  additionalContext?: string
): string {
  const summary = workerCase.summary || "Workplace injury (details pending)";
  const constraints = workerCase.clinical_status_json?.medicalConstraints;
  const capacity = workerCase.clinical_status_json?.functionalCapacity;

  const constraintsText = constraints
    ? `
MEDICAL CONSTRAINTS:
${constraints.noLiftingOverKg ? `- No lifting over ${constraints.noLiftingOverKg}kg` : ""}
${constraints.noBending ? "- No bending" : ""}
${constraints.noTwisting ? "- No twisting" : ""}
${constraints.noProlongedStanding ? "- No prolonged standing" : ""}
${constraints.noProlongedSitting ? "- No prolonged sitting" : ""}
${constraints.otherConstraints || ""}
`.trim()
    : "No medical constraints documented.";

  const capacityText = capacity
    ? `
FUNCTIONAL CAPACITY:
${capacity.canLiftKg !== undefined ? `- Can lift: ${capacity.canLiftKg}kg` : ""}
${capacity.canStandMinutes !== undefined ? `- Can stand: ${capacity.canStandMinutes} minutes` : ""}
${capacity.canSitMinutes !== undefined ? `- Can sit: ${capacity.canSitMinutes} minutes` : ""}
${capacity.maxWorkHoursPerDay !== undefined ? `- Max work hours/day: ${capacity.maxWorkHoursPerDay}` : ""}
`.trim()
    : "No functional capacity assessment documented.";

  return `You are a care coordination assistant helping case managers develop treatment plans for workplace injury cases in Australia.

IMPORTANT: You are providing ADVISORY RECOMMENDATIONS only, NOT medical treatment decisions. All recommendations must be reviewed and approved by qualified healthcare professionals.

CASE INFORMATION:
- Worker: [REDACTED - no PII in prompts]
- Injury: ${summary}
- Risk Level: ${workerCase.riskLevel}
- Work Status: ${workerCase.workStatus}
- Date of Injury: ${workerCase.dateOfInjury}

${constraintsText}

${capacityText}

RECOVERY ESTIMATE:
- Expected duration: ${recoveryEstimate.estimatedWeeks || 12} weeks
- Confidence: ${recoveryEstimate.confidence || "medium"}

CLINICAL FLAGS:
${clinicalFlags.length > 0 ? clinicalFlags.map((f) => `- ${f}`).join("\n") : "No clinical flags"}

${additionalContext ? `<user_provided_context>\n${sanitizeUserInput(additionalContext)}\n</user_provided_context>\n` : ""}

Generate a structured treatment plan with:
1. **Interventions**: Specific treatment types (physiotherapy, medication, specialist referrals, workplace modifications, etc.)
2. **Milestones**: Week-by-week recovery checkpoints
3. **Expected Outcomes**: What success looks like
4. **Specialist Referrals**: If needed (orthopedic, pain specialist, psychologist, etc.)
5. **Success Criteria**: Objective measures

Return ONLY valid JSON matching this exact structure (no markdown, no code blocks):

{
  "interventions": [
    {
      "type": "physiotherapy" | "medication" | "specialist" | "surgical" | "workplace_modification" | "psychological" | "other",
      "description": "Specific intervention description",
      "frequency": "e.g., 3x per week",
      "duration": "e.g., 6 weeks",
      "priority": "critical" | "recommended" | "optional"
    }
  ],
  "milestones": [
    {
      "weekNumber": 2,
      "description": "Milestone description",
      "expectedOutcome": "Expected result"
    }
  ],
  "specialistReferrals": ["Specialist type if needed"],
  "expectedDurationWeeks": 8,
  "expectedOutcomes": ["Return to full duties", "Pain-free movement"],
  "successCriteria": ["Objective measure 1", "Objective measure 2"],
  "factorsConsidered": ["Factor 1", "Factor 2"]
}

Focus on practical, achievable interventions appropriate for Australian workplace injury management under WorkSafe Victoria guidelines.`;
}

/**
 * Calculate confidence score based on data quality
 */
function calculateConfidence(workerCase: WorkerCase, aiResponse: AITreatmentPlanResponse): number {
  let confidence = 50; // Base confidence

  // Increase confidence for good data
  if (workerCase.summary && workerCase.summary.length > 50) confidence += 10;
  if (workerCase.clinical_status_json?.medicalConstraints) confidence += 10;
  if (workerCase.clinical_status_json?.functionalCapacity) confidence += 10;
  if (workerCase.hasCertificate) confidence += 10;
  if (workerCase.riskLevel === "Low") confidence += 10;

  // Decrease confidence for missing data or high risk
  if (!workerCase.summary || workerCase.summary.length < 20) confidence -= 15;
  if (workerCase.riskLevel === "High") confidence -= 10;
  if (aiResponse.interventions.length === 0) confidence -= 20;

  // Clamp between 0-100
  return Math.max(0, Math.min(100, confidence));
}

/**
 * Create fallback plan when AI fails
 */
function createFallbackPlan(workerCase: WorkerCase): TreatmentPlan {
  const id = randomUUID();
  const now = new Date().toISOString();

  return {
    id,
    status: "active",
    generatedAt: now,
    generatedBy: "ai",
    aiModel: MODEL,
    confidence: 30, // Low confidence for fallback
    injuryType: "unknown",
    interventions: [
      {
        type: "other",
        description: "Consult with treating medical practitioner for treatment plan",
        priority: "critical",
      },
    ],
    milestones: [
      {
        weekNumber: 2,
        description: "Initial review",
        expectedOutcome: "Treatment plan established with medical practitioner",
      },
    ],
    expectedDurationWeeks: 12,
    expectedOutcomes: ["Medical treatment plan established", "Recovery progressing as expected"],
    factorsConsidered: ["AI generation failed - manual review required"],
    disclaimerText: DISCLAIMER_TEXT,
  };
}

/**
 * Generate treatment plan using Claude AI
 */
export async function generateTreatmentPlan(
  storage: IStorage,
  request: GenerateTreatmentPlanRequest
): Promise<TreatmentPlan> {
  const { caseId, organizationId, additionalContext } = request;

  // Fetch case
  const workerCase = await storage.getGPNet2CaseById(caseId, organizationId);
  if (!workerCase) {
    throw new Error("Case not found");
  }

  try {
    // Fetch context and estimate recovery timeline
    const context = await fetchCaseContext(storage, caseId, organizationId);
    const clinicalEvidence = evaluateClinicalEvidence(workerCase);
    const recoveryEstimate = calculateRecoveryTimeline({
      dateOfInjury: workerCase.dateOfInjury,
      summary: workerCase.summary || "",
      riskLevel: workerCase.riskLevel as "High" | "Medium" | "Low",
      clinicalFlags: clinicalEvidence.flags || [],
    });

    // Build prompt
    const prompt = buildTreatmentPrompt(
      workerCase,
      recoveryEstimate,
      clinicalEvidence.flags.map((f) => f.message),
      additionalContext
    );

    // Call Claude API with timeout
    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const response = await Promise.race([
      anthropic.messages.create({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        messages: [{ role: "user", content: prompt }],
      }),
      new Promise((_, reject) => setTimeout(() => reject(new Error("Timeout")), TIMEOUT_MS)),
    ]) as Anthropic.Message;

    // Parse AI response
    const textContent = response.content.find((c) => c.type === "text");
    if (!textContent || textContent.type !== "text") {
      console.error("[TreatmentPlan] No text content in AI response");
      return createFallbackPlan(workerCase);
    }

    let aiResponse: AITreatmentPlanResponse;
    try {
      aiResponse = JSON.parse(textContent.text);
    } catch (parseError) {
      console.error("[TreatmentPlan] JSON parse error:", parseError);
      return createFallbackPlan(workerCase);
    }

    // Build treatment plan
    const id = randomUUID();
    const now = new Date().toISOString();
    const confidence = calculateConfidence(workerCase, aiResponse);

    const plan: TreatmentPlan = {
      id,
      status: "active",
      generatedAt: now,
      generatedBy: "ai",
      aiModel: MODEL,
      confidence,
      injuryType: workerCase.summary || "unknown",
      diagnosisSummary: workerCase.summary,
      interventions: aiResponse.interventions,
      specialistReferrals: aiResponse.specialistReferrals,
      expectedDurationWeeks: aiResponse.expectedDurationWeeks,
      milestones: aiResponse.milestones,
      expectedOutcomes: aiResponse.expectedOutcomes,
      successCriteria: aiResponse.successCriteria,
      factorsConsidered: aiResponse.factorsConsidered,
      disclaimerText: DISCLAIMER_TEXT,
    };

    // Supersede existing plan if present
    const existingStatus = workerCase.clinical_status_json || {};
    const existingPlan = existingStatus.treatmentPlan;
    const history = existingStatus.treatmentPlanHistory || [];

    if (existingPlan && existingPlan.status === "active") {
      // Create new superseded plan object (immutable update)
      const supersededPlan: TreatmentPlan = {
        ...existingPlan,
        status: "superseded",
        supersededAt: now,
        supersededBy: id,
      };
      history.push(supersededPlan);
    }

    // Update case with new plan
    const updatedStatus: CaseClinicalStatus = {
      ...existingStatus,
      treatmentPlan: plan,
      treatmentPlanHistory: history,
    };

    await storage.updateClinicalStatus(caseId, organizationId, updatedStatus);

    // Audit log (no PII)
    await logAuditEvent({
      organizationId,
      eventType: "ai.treatment_plan.generate" as any,
      userId: null,
      resourceType: "treatment_plan",
      resourceId: plan.id,
      metadata: {
        caseId,
        confidence: plan.confidence,
        interventionCount: plan.interventions.length,
      },
    });

    console.log(`[TreatmentPlan] Generated plan ${id} for case ${caseId} (confidence: ${confidence}%)`);
    return plan;
  } catch (error) {
    console.error("[TreatmentPlan] Error generating plan:", error);
    throw error;
  }
}

/**
 * Get current treatment plan for a case
 */
export async function getTreatmentPlan(
  storage: IStorage,
  caseId: string,
  organizationId: string
): Promise<TreatmentPlan | null> {
  const workerCase = await storage.getGPNet2CaseById(caseId, organizationId);
  if (!workerCase) {
    return null;
  }

  return workerCase.clinical_status_json?.treatmentPlan || null;
}

/**
 * Update treatment plan status or notes
 */
export async function updateTreatmentPlan(
  storage: IStorage,
  caseId: string,
  organizationId: string,
  planId: string,
  updates: UpdateTreatmentPlanRequest
): Promise<TreatmentPlan> {
  const workerCase = await storage.getGPNet2CaseById(caseId, organizationId);
  if (!workerCase) {
    throw new Error("Case not found");
  }

  const existingStatus = workerCase.clinical_status_json || {};
  const plan = existingStatus.treatmentPlan;

  if (!plan || plan.id !== planId) {
    throw new Error("Treatment plan not found");
  }

  // Apply updates
  if (updates.status) {
    plan.status = updates.status;
    if (updates.status === "completed") {
      plan.completedAt = new Date().toISOString();
    }
  }

  if (updates.notes !== undefined) {
    plan.notes = updates.notes;
  }

  // Save updated plan
  const updatedStatus: CaseClinicalStatus = {
    ...existingStatus,
    treatmentPlan: plan,
  };

  await storage.updateClinicalStatus(caseId, organizationId, updatedStatus);

  // Audit log
  await logAuditEvent({
    organizationId,
    eventType: "ai.treatment_plan.update" as any,
    userId: null,
    resourceType: "treatment_plan",
    resourceId: planId,
    metadata: { caseId, updates },
  });

  console.log(`[TreatmentPlan] Updated plan ${planId} for case ${caseId}`);
  return plan;
}
