import { useState, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { GlassPanel } from "./ui/glass-panel";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "./ui/dialog";
import type { TreatmentPlan, TreatmentIntervention, TreatmentPriority } from "@shared/schema";
import { fetchWithCsrf, getAuthHeaders } from "../lib/queryClient";

interface RecoveryData {
  analysis?: {
    comparedToExpected: string;
    weeksDifference: number | null;
    trend: string;
  };
  currentCapacityPercentage?: number;
  weeksElapsed?: number;
  injuryType?: string;
  injuryTypeLabel?: string;
  diagnosticRecommendations?: Array<{
    severity: string;
    title: string;
    description: string;
  }>;
}

interface TreatmentPlanCardProps {
  caseId: string;
  recoveryData?: RecoveryData;
  autoGenerate?: boolean;
}

// Demo fallback treatment plan for when API fails
const DEMO_FALLBACK_PLAN: TreatmentPlan = {
  id: "demo-plan",
  status: "active",
  generatedAt: new Date().toISOString(),
  generatedBy: "ai",
  aiModel: "demo-fallback",
  confidence: 75,
  injuryType: "Musculoskeletal injury",
  diagnosisSummary: "Lower back strain with associated muscle spasm",
  interventions: [
    { type: "physiotherapy", description: "Progressive strengthening exercises focusing on core stability", frequency: "3x per week", duration: "6 weeks", priority: "critical" },
    { type: "medication", description: "NSAIDs for pain management as needed", priority: "recommended" },
    { type: "workplace_modification", description: "Ergonomic workstation assessment and adjustments", priority: "recommended" },
  ],
  milestones: [
    { weekNumber: 2, description: "Initial pain reduction", expectedOutcome: "50% pain reduction, able to perform light duties" },
    { weekNumber: 4, description: "Increased mobility", expectedOutcome: "Resume modified duties with restrictions" },
    { weekNumber: 8, description: "Return to full duties", expectedOutcome: "Full work capacity restored" },
  ],
  expectedDurationWeeks: 8,
  expectedOutcomes: ["Return to full work capacity", "No ongoing medication required", "Pain-free movement"],
  specialistReferrals: ["Physiotherapist"],
  factorsConsidered: ["Injury type", "Work demands", "Recovery timeline"],
  disclaimerText: "ADVISORY ONLY - This is a demonstration plan. All treatment decisions must be made by qualified healthcare professionals.",
};

export function TreatmentPlanCard({ caseId, recoveryData: externalRecoveryData, autoGenerate = true }: TreatmentPlanCardProps) {
  const [plan, setPlan] = useState<TreatmentPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [showPlateauAlert, setShowPlateauAlert] = useState(false);
  const [usedFallback, setUsedFallback] = useState(false);

  // Fetch recovery data if not provided externally (will be cached by TanStack Query)
  const { data: fetchedRecoveryData } = useQuery<RecoveryData>({
    queryKey: [`/api/cases/${caseId}/recovery-chart`],
    enabled: !!caseId && !externalRecoveryData,
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Use external data if provided, otherwise use fetched data
  const recoveryData = externalRecoveryData || fetchedRecoveryData;

  // Detect recovery plateau
  const isRecoveryPlateau = recoveryData?.analysis?.trend === 'stable' &&
    recoveryData?.analysis?.comparedToExpected === 'behind' &&
    (recoveryData?.weeksElapsed || 0) > 8;

  // Check if plan is stale (generated more than 4 weeks ago while recovery is behind)
  const isPlanStale = plan && recoveryData?.analysis?.comparedToExpected === 'behind' && (() => {
    const generatedDate = new Date(plan.generatedAt);
    const fourWeeksAgo = new Date();
    fourWeeksAgo.setDate(fourWeeksAgo.getDate() - 28);
    return generatedDate < fourWeeksAgo;
  })();

  useEffect(() => {
    let cancelled = false;

    const fetchPlan = async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await fetch(`/api/cases/${caseId}/treatment-plan`, {
          credentials: "include",
          headers: getAuthHeaders(),
        });
        if (response.status === 404) {
          // No plan exists yet - this is expected
          if (cancelled) return;
          setPlan(null);
          setLoading(false);
          return;
        }
        if (!response.ok) {
          throw new Error("Failed to fetch treatment plan");
        }
        const data = await response.json();
        if (cancelled) return;
        setPlan(data);
      } catch (err) {
        if (cancelled) return;
        // Use fallback plan when fetch fails
        console.warn("Treatment plan fetch failed, using fallback:", err);
        setPlan(DEMO_FALLBACK_PLAN);
        setUsedFallback(true);
        setError(null);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    fetchPlan();
    return () => {
      cancelled = true;
    };
  }, [caseId]);

  // Auto-generate treatment plan if none exists and autoGenerate is enabled
  useEffect(() => {
    if (!loading && !plan && !hasAutoGenerated && autoGenerate && !error) {
      setHasAutoGenerated(true);
      generatePlan();
    }
  }, [loading, plan, hasAutoGenerated, autoGenerate, error]);

  // Show plateau alert when detected
  useEffect(() => {
    if (isRecoveryPlateau && plan && !showPlateauAlert) {
      setShowPlateauAlert(true);
    }
  }, [isRecoveryPlateau, plan]);

  const generatePlan = async () => {
    setGenerating(true);
    setError(null);
    try {
      // Build additional context from recovery data
      let additionalContext = "";
      if (recoveryData) {
        const contextParts: string[] = [];

        if (recoveryData.analysis?.comparedToExpected === 'behind') {
          contextParts.push(`Recovery is BEHIND schedule by ${Math.abs(recoveryData.analysis.weeksDifference || 0)} weeks.`);
        }

        if (isRecoveryPlateau) {
          contextParts.push("RECOVERY PLATEAU DETECTED: Worker's capacity has plateaued at " +
            `${recoveryData.currentCapacityPercentage}% for an extended period.`);
          contextParts.push("Consider additional diagnostic tests or specialist referrals to identify underlying factors.");
        }

        if (recoveryData.injuryTypeLabel) {
          contextParts.push(`Injury type: ${recoveryData.injuryTypeLabel}`);
        }

        if (recoveryData.diagnosticRecommendations?.length) {
          const criticalRecs = recoveryData.diagnosticRecommendations
            .filter(r => r.severity === 'critical' || r.severity === 'warning')
            .map(r => r.title);
          if (criticalRecs.length > 0) {
            contextParts.push(`Active recommendations: ${criticalRecs.join(', ')}`);
          }
        }

        additionalContext = contextParts.join(' ');
      }

      const response = await fetchWithCsrf(`/api/cases/${caseId}/treatment-plan/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ additionalContext }),
      });
      if (!response.ok) {
        throw new Error("Failed to generate treatment plan");
      }
      const data = await response.json();
      setPlan(data);
      setUsedFallback(false);
      setShowPlateauAlert(false); // Reset alert after regeneration
    } catch (err) {
      console.warn("Treatment plan generation failed, using fallback:", err);
      // Use fallback plan when generation fails
      setPlan(DEMO_FALLBACK_PLAN);
      setUsedFallback(true);
      setError(null);
    } finally {
      setGenerating(false);
    }
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    if (Number.isNaN(date.getTime())) return "Unknown";
    return date.toLocaleDateString("en-AU", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  };

  const priorityBadgeClass = (priority?: TreatmentPriority) => {
    switch (priority) {
      case "critical":
        return "bg-gradient-to-r from-red-500 to-pink-500 text-white border-red-300 shadow-lg shadow-red-500/25";
      case "recommended":
        return "bg-gradient-to-r from-amber-500 to-orange-500 text-white border-amber-300 shadow-lg shadow-amber-500/25";
      case "optional":
        return "bg-gradient-to-r from-slate-400 to-slate-500 text-white border-slate-300 shadow-lg shadow-slate-500/25";
      default:
        return "bg-gradient-to-r from-slate-400 to-slate-500 text-white border-slate-300 shadow-lg shadow-slate-500/25";
    }
  };

  const priorityLabel = (priority?: TreatmentPriority) => {
    switch (priority) {
      case "critical":
        return "CRITICAL";
      case "recommended":
        return "RECOMMENDED";
      case "optional":
        return "OPTIONAL";
      default:
        return "";
    }
  };

  const interventionTypeIcon = (type: TreatmentIntervention["type"]) => {
    switch (type) {
      case "physiotherapy":
        return "medical_services";
      case "medication":
        return "medication";
      case "specialist":
        return "stethoscope";
      case "surgical":
        return "surgical";
      case "workplace_modification":
        return "engineering";
      case "psychological":
        return "psychology";
      case "diagnostic":
        return "labs";
      default:
        return "health_and_safety";
    }
  };

  const confidenceColor = (confidence: number) => {
    if (confidence >= 75) return "text-emerald-700";
    if (confidence >= 50) return "text-amber-700";
    return "text-red-700";
  };

  return (
    <GlassPanel
      className="treatment-plan-glass-card"
      variant="gradient"
      data-testid="card-treatment-plan"
    >
      <div className="p-6">
        <div className="border-b border-white/20 pb-4 mb-6">
          <h3 className="flex items-center gap-2 text-base font-semibold text-white">
            <span className="material-symbols-outlined text-white/90">fact_check</span>
            Treatment Plan
          </h3>
        </div>
        <div>
        {loading && (
          <div className="flex items-center gap-3 text-sm text-muted-foreground">
            <span className="material-symbols-outlined animate-spin text-primary">progress_activity</span>
            <span>Loading treatment plan...</span>
          </div>
        )}

        {error && (
          <div className="text-sm text-muted-foreground flex items-center gap-2">
            <span className="material-symbols-outlined text-warning text-base">error</span>
            {error}
          </div>
        )}

        {/* Recovery Plateau Alert */}
        {showPlateauAlert && plan && isRecoveryPlateau && (
          <div className="rounded-md border-2 border-orange-400 bg-orange-50 p-4 mb-4">
            <div className="flex items-start gap-3">
              <span className="material-symbols-outlined text-orange-600 text-2xl">trending_flat</span>
              <div className="flex-1">
                <h4 className="text-sm font-bold text-orange-900 mb-1">
                  Recovery Plateau Detected
                </h4>
                <p className="text-xs text-orange-800 mb-3">
                  Worker's capacity has plateaued at {recoveryData?.currentCapacityPercentage}% for an extended period.
                  Based on the injury type ({recoveryData?.injuryTypeLabel || 'unknown'}), consider:
                </p>
                <ul className="text-xs text-orange-800 space-y-1 mb-3">
                  <li className="flex items-center gap-1">
                    <span className="w-1.5 h-1.5 bg-orange-500 rounded-full"></span>
                    Additional diagnostic imaging (MRI, CT scan)
                  </li>
                  <li className="flex items-center gap-1">
                    <span className="w-1.5 h-1.5 bg-orange-500 rounded-full"></span>
                    Specialist review (orthopedic, pain management)
                  </li>
                  <li className="flex items-center gap-1">
                    <span className="w-1.5 h-1.5 bg-orange-500 rounded-full"></span>
                    Treatment plan modification
                  </li>
                </ul>
                <Button
                  size="sm"
                  onClick={generatePlan}
                  disabled={generating}
                  className="bg-orange-600 hover:bg-orange-700 text-white gap-2"
                >
                  {generating ? (
                    <>
                      <span className="material-symbols-outlined animate-spin text-sm">progress_activity</span>
                      Regenerating...
                    </>
                  ) : (
                    <>
                      <span className="material-symbols-outlined text-sm">auto_fix_high</span>
                      Regenerate Plan with Plateau Analysis
                    </>
                  )}
                </Button>
              </div>
              <button
                onClick={() => setShowPlateauAlert(false)}
                className="text-orange-400 hover:text-orange-600"
              >
                <span className="material-symbols-outlined text-lg">close</span>
              </button>
            </div>
          </div>
        )}

        {/* Stale Plan Warning */}
        {isPlanStale && !showPlateauAlert && (
          <div className="rounded-md border border-blue-300 bg-blue-50 p-3 mb-4">
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-blue-600 text-lg">update</span>
              <div className="flex-1">
                <p className="text-xs text-blue-800">
                  Treatment plan may be outdated. Recovery is behind schedule.
                </p>
              </div>
              <Button
                size="sm"
                variant="outline"
                onClick={generatePlan}
                disabled={generating}
                className="text-xs border-blue-400 text-blue-700 hover:bg-blue-100"
              >
                {generating ? "Updating..." : "Update Plan"}
              </Button>
            </div>
          </div>
        )}

        {/* No plan exists - show generate button */}
        {!loading && !error && !plan && (
          <div className="text-center py-6">
            <span className="material-symbols-outlined text-4xl text-muted-foreground/50 mb-3 block">
              clinical_notes
            </span>
            <p className="text-sm text-muted-foreground mb-4">
              No treatment plan generated yet for this case.
            </p>
            <Button
              onClick={generatePlan}
              disabled={generating}
              className="gap-2"
              data-testid="button-generate-plan"
            >
              {generating ? (
                <>
                  <span className="material-symbols-outlined animate-spin text-base">progress_activity</span>
                  <span>Generating with AI...</span>
                </>
              ) : (
                <>
                  <span className="material-symbols-outlined text-base">auto_awesome</span>
                  <span>Generate Treatment Plan</span>
                </>
              )}
            </Button>
          </div>
        )}

        {/* Plan exists - show details */}
        {!loading && !error && plan && (
          <div className="space-y-4">
            {/* Disclaimer - ADVISORY ONLY */}
            <div className="rounded-md border-2 border-amber-300 bg-amber-50 p-3">
              <div className="flex items-start gap-2">
                <span className="material-symbols-outlined text-amber-700 text-xl mt-0.5">warning</span>
                <div className="flex-1">
                  <p className="text-xs font-bold text-amber-900 uppercase tracking-wide mb-1">
                    ⚠️ Advisory Only {usedFallback && <span className="text-blue-700">(Demo Mode)</span>}
                  </p>
                  <p className="text-xs text-amber-800 leading-relaxed">
                    {usedFallback
                      ? "This is a demonstration treatment plan shown for preview purposes. Connect to AI service for personalized recommendations."
                      : "This treatment plan is AI-generated for care coordination purposes only. It does NOT constitute medical advice. All treatment decisions must be made by qualified healthcare professionals."}
                  </p>
                </div>
              </div>
            </div>

            {/* Confidence & Metadata */}
            <div className="flex items-center justify-between text-xs">
              <div className="flex items-center gap-2 text-muted-foreground">
                <span className="material-symbols-outlined text-sm">event</span>
                <span>Generated {formatDate(plan.generatedAt)}</span>
              </div>
              <div className={`confidence-indicator animate-pulse-slow flex items-center gap-1 font-semibold ${confidenceColor(plan.confidence)}`}>
                <span className="material-symbols-outlined text-sm">insights</span>
                <span>{plan.confidence}% confidence</span>
              </div>
            </div>

            {/* Expected Duration */}
            <div className="rounded-md border border-border p-3 bg-slate-50/50">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-primary text-lg">schedule</span>
                  <span className="text-sm font-medium">Expected Duration</span>
                </div>
                <Badge variant="outline" className="text-xs">
                  {plan.expectedDurationWeeks} weeks
                </Badge>
              </div>
            </div>

            {/* Interventions */}
            {plan.interventions && plan.interventions.length > 0 && (
              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="material-symbols-outlined text-sm">medical_services</span>
                  Interventions ({plan.interventions.length})
                </h4>
                <div className="space-y-2">
                  {plan.interventions.slice(0, 5).map((intervention, idx) => (
                    <div
                      key={idx}
                      className="rounded-md border border-border p-3 bg-white"
                    >
                      <div className="flex items-start gap-2">
                        <span className="material-symbols-outlined text-primary text-lg mt-0.5">
                          {interventionTypeIcon(intervention.type)}
                        </span>
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            {intervention.priority && (
                              <Badge
                                variant="outline"
                                className={`intervention-badge ${intervention.priority} text-[10px] font-semibold ${priorityBadgeClass(intervention.priority)}`}
                              >
                                {priorityLabel(intervention.priority)}
                              </Badge>
                            )}
                            <span className="text-[10px] text-muted-foreground uppercase tracking-wide">
                              {intervention.type.replace("_", " ")}
                            </span>
                          </div>
                          <p className="text-sm text-card-foreground">{intervention.description}</p>
                          {(intervention.frequency || intervention.duration) && (
                            <div className="mt-1 text-xs text-muted-foreground flex flex-wrap gap-3">
                              {intervention.frequency && (
                                <span className="flex items-center gap-1">
                                  <span className="material-symbols-outlined text-xs">repeat</span>
                                  {intervention.frequency}
                                </span>
                              )}
                              {intervention.duration && (
                                <span className="flex items-center gap-1">
                                  <span className="material-symbols-outlined text-xs">timer</span>
                                  {intervention.duration}
                                </span>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                  {plan.interventions.length > 5 && (
                    <Dialog>
                      <DialogTrigger asChild>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-xs text-primary hover:bg-transparent w-full"
                        >
                          View all {plan.interventions.length} interventions
                        </Button>
                      </DialogTrigger>
                      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
                        <DialogHeader>
                          <DialogTitle>All Treatment Interventions</DialogTitle>
                        </DialogHeader>
                        <div className="space-y-3 mt-4">
                          {plan.interventions.map((intervention, idx) => (
                            <div key={idx} className="rounded-md border border-border p-3">
                              <div className="flex items-start gap-2">
                                <span className="material-symbols-outlined text-primary text-lg">
                                  {interventionTypeIcon(intervention.type)}
                                </span>
                                <div className="flex-1">
                                  <div className="flex items-center gap-2 mb-1">
                                    {intervention.priority && (
                                      <Badge
                                        variant="outline"
                                        className={`text-[10px] ${priorityBadgeClass(intervention.priority)}`}
                                      >
                                        {priorityLabel(intervention.priority)}
                                      </Badge>
                                    )}
                                    <span className="text-[10px] text-muted-foreground uppercase">
                                      {intervention.type.replace("_", " ")}
                                    </span>
                                  </div>
                                  <p className="text-sm">{intervention.description}</p>
                                  {(intervention.frequency || intervention.duration) && (
                                    <div className="mt-1 text-xs text-muted-foreground flex gap-3">
                                      {intervention.frequency && <span>Frequency: {intervention.frequency}</span>}
                                      {intervention.duration && <span>Duration: {intervention.duration}</span>}
                                    </div>
                                  )}
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      </DialogContent>
                    </Dialog>
                  )}
                </div>
              </div>
            )}

            {/* Milestones */}
            {plan.milestones && plan.milestones.length > 0 && (
              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="material-symbols-outlined text-sm">flag</span>
                  Recovery Milestones ({plan.milestones.length})
                </h4>
                <div className="space-y-2">
                  {plan.milestones.slice(0, 3).map((milestone, idx) => (
                    <div
                      key={idx}
                      className="rounded-md border border-border p-3 bg-white"
                    >
                      <div className="flex items-start gap-2">
                        <Badge variant="outline" className="text-[10px] bg-primary/10 text-primary border-primary/20">
                          Week {milestone.weekNumber}
                        </Badge>
                        <div className="flex-1">
                          <p className="text-sm font-medium text-card-foreground">
                            {milestone.description}
                          </p>
                          <p className="text-xs text-muted-foreground mt-1">
                            Expected: {milestone.expectedOutcome}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                  {plan.milestones.length > 3 && (
                    <Dialog>
                      <DialogTrigger asChild>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-xs text-primary hover:bg-transparent w-full"
                        >
                          View all {plan.milestones.length} milestones
                        </Button>
                      </DialogTrigger>
                      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
                        <DialogHeader>
                          <DialogTitle>Recovery Milestones Timeline</DialogTitle>
                        </DialogHeader>
                        <div className="space-y-3 mt-4">
                          {plan.milestones.map((milestone, idx) => (
                            <div key={idx} className="rounded-md border border-border p-3">
                              <div className="flex items-start gap-2">
                                <Badge variant="outline" className="text-[10px] bg-primary/10 text-primary">
                                  Week {milestone.weekNumber}
                                </Badge>
                                <div className="flex-1">
                                  <p className="text-sm font-medium">{milestone.description}</p>
                                  <p className="text-xs text-muted-foreground mt-1">
                                    Expected: {milestone.expectedOutcome}
                                  </p>
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      </DialogContent>
                    </Dialog>
                  )}
                </div>
              </div>
            )}

            {/* Expected Outcomes */}
            {plan.expectedOutcomes && plan.expectedOutcomes.length > 0 && (
              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="material-symbols-outlined text-sm">check_circle</span>
                  Expected Outcomes
                </h4>
                <ul className="space-y-1">
                  {plan.expectedOutcomes.map((outcome, idx) => (
                    <li key={idx} className="flex items-start gap-2 text-sm text-card-foreground">
                      <span className="material-symbols-outlined text-emerald-600 text-base mt-0.5">task_alt</span>
                      <span>{outcome}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Specialist Referrals */}
            {plan.specialistReferrals && plan.specialistReferrals.length > 0 && (
              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="material-symbols-outlined text-sm">stethoscope</span>
                  Specialist Referrals
                </h4>
                <div className="flex flex-wrap gap-2">
                  {plan.specialistReferrals.map((specialist, idx) => (
                    <Badge key={idx} variant="outline" className="text-xs">
                      {specialist}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {/* Diagnostic Tests */}
            {plan.diagnosticTests && plan.diagnosticTests.length > 0 && (
              <div>
                <h4 className="text-xs font-semibold uppercase text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="material-symbols-outlined text-sm">labs</span>
                  Recommended Diagnostic Tests
                </h4>
                <div className="flex flex-wrap gap-2">
                  {plan.diagnosticTests.map((test, idx) => (
                    <Badge key={idx} variant="outline" className="text-xs bg-blue-50 text-blue-700 border-blue-300">
                      {test}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            {/* Plateau Analysis */}
            {plan.plateauAnalysis && (
              <div className="rounded-md border-2 border-orange-300 bg-orange-50 p-3">
                <div className="flex items-start gap-2">
                  <span className="material-symbols-outlined text-orange-600 text-lg mt-0.5">trending_flat</span>
                  <div>
                    <h4 className="text-xs font-bold text-orange-900 uppercase mb-1">
                      Plateau Analysis
                    </h4>
                    <p className="text-sm text-orange-800">{plan.plateauAnalysis}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Regenerate Button */}
            <div className="pt-2 border-t border-border">
              <Button
                variant="outline"
                size="sm"
                onClick={generatePlan}
                disabled={generating}
                className="w-full gap-2"
                data-testid="button-regenerate-plan"
              >
                {generating ? (
                  <>
                    <span className="material-symbols-outlined animate-spin text-sm">progress_activity</span>
                    <span>Regenerating...</span>
                  </>
                ) : (
                  <>
                    <span className="material-symbols-outlined text-sm">refresh</span>
                    <span>Regenerate Plan</span>
                  </>
                )}
              </Button>
            </div>
          </div>
        )}
        </div>
      </div>
    </GlassPanel>
  );
}
